name = "devbox-ssh-service"
main = "dist/index.js"
compatibility_date = "2025-04-19"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm install && npx esbuild src/index.ts --bundle --outfile=dist/index.js --platform=node --external:*.node --format=esm"

[vars]
SSH_SERVICE_SECRET = "change-me-later"
