name = "devboxui"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[vars]
# You can leave secrets in the Cloudflare Dashboard UI.
# Only non-sensitive config goes here if needed.
